apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: maven-webapp
spec:
  replicas: 1
  selector:
    app: maven-webapp
  template:
    metadata:
      labels:
        app: maven-webapp
    spec:
      containers:
      - name: maven-webapp
        image: ''
        ports:
        - containerPort: 8080
          protocol: TCP
  triggers:
  - type: ConfigChange 
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - maven-webapp
      from:
        kind: ImageStreamTag
        name: maven-webapp:latest