apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wso2is-service
spec:
  port:
    targetPort: servlet-https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: wso2is-service