apiVersion: v1
kind: Service
metadata:
  name: wso2is-service
spec:
  selector:
    app: wso2is
  type: ClusterIP
  ports:
  - name: servlet-https
    port: 9443
    protocol: TCP
    targetPort: 9443